# We want to run quarantined tests on master as well as on PRs
trigger:
  batch: true
  branches:
    include:
    - master

schedules:
- cron: "0 */4 * * *"
  displayName: Every 4 hours test run
  branches:
    include:
    - master
  always: true

variables:
- ${{ if ne(variables['System.TeamProject'], 'internal') }}:
  - name: _UseHelixOpenQueues
    value: 'true'
- ${{ if eq(variables['System.TeamProject'], 'internal') }}:
  - group: DotNet-HelixApi-Access
  - name: _UseHelixOpenQueues
    value: 'false'

jobs:
- template: jobs/default-build.yml
  parameters:
    jobName: Helix_quarantine_x64
    jobDisplayName: 'Tests: Helix Quarantine x64'
    agentOs: Windows
    timeoutInMinutes: 240
    steps:
    # Build the shared framework
    - script: ./build.cmd -ci -all -pack -arch x64 /p:ASPNETCORE_TEST_LOG_DIR=artifacts/log /bl:artifacts/log/helix.build.x64.binlog
      displayName: Build shared fx
    - script: .\restore.cmd -ci /p:BuildInteropProjects=true
      displayName: Restore interop projects
    - script: .\build.cmd -ci -NoRestore -test -noBuildJava -all -projects eng\helix\helix.proj /p:RunQuarantinedTests=true /p:IsRequiredCheck=true /p:IsHelixJob=true /p:BuildInteropProjects=true /p:RunTemplateTests=true /p:ASPNETCORE_TEST_LOG_DIR=artifacts/log -bl
      displayName: Run build.cmd helix target
      env:
        HelixApiAccessToken: $(HelixApiAccessToken) # Needed for internal queues
        SYSTEM_ACCESSTOKEN: $(System.AccessToken) # We need to set this env var to publish helix results to Azure Dev Ops
    artifacts:
    - name: Helix_logs
      path: artifacts/log/
      publishOnError: true

- template: jobs/default-build.yml
  parameters:
    jobName: Windows_Quarantine_x64
    jobDisplayName: 'Tests: Quarantine Windows x64'
    agentOs: Windows
    timeoutInMinutes: 240
    steps:
    - powershell: "& ./build.ps1 -CI -nobl -NoBuild -Test /p:RunQuarantinedTests=true"
      displayName: Run Quarantined Tests
      continueOnError: true
    - task: PublishTestResults@2
      displayName: Publish Quarantined Test Results
      inputs:
        testResultsFormat: 'xUnit'
        testResultsFiles: '*.xml'
        searchFolder: '$(Build.SourcesDirectory)/artifacts/TestResults/$(_BuildConfig)/Quarantined'

- template: jobs/default-build.yml
  parameters:
    jobName: MacOS_Quarantine_Test
    jobDisplayName: "Tests: Quarantine macOS 10.14"
    agentOs: macOS
    timeoutInMinutes: 240
    steps:
    - bash: ./build.sh --no-build --ci --nobl --test -p:RunQuarantinedTests=true
      displayName: Run Quarantined Tests
      continueOnError: true
    - task: PublishTestResults@2
      displayName: Publish Quarantined Test Results
      inputs:
        testResultsFormat: 'xUnit'
        testResultsFiles: '*.xml'
        searchFolder: '$(Build.SourcesDirectory)/artifacts/TestResults/$(_BuildConfig)/Quarantined'

- template: jobs/default-build.yml
  parameters:
    jobName: Linux_Quarantine_Test
    jobDisplayName: "Tests: Quarantine Ubuntu 16.04 x64"
    agentOs: Linux
    timeoutInMinutes: 240
    steps:
    - bash: ./build.sh --no-build --ci --nobl --test -p:RunQuarantinedTests=true
      displayName: Run Quarantined Tests
      continueOnError: true
    - task: PublishTestResults@2
      displayName: Publish Quarantined Test Results
      inputs:
        testResultsFormat: 'xUnit'
        testResultsFiles: '*.xml'
        searchFolder: '$(Build.SourcesDirectory)/artifacts/TestResults/$(_BuildConfig)/Quarantined'